<?php
/**
 * Indicia, the OPAL Online Recording Toolkit.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/gpl.html.
 *
 * @package Client
 * @subpackage PrebuiltForms
 * @author  Indicia Team
 * @license http://www.gnu.org/licenses/gpl.html GPL 3.0
 * @link  http://code.google.com/p/indicia/
 */

require_once('sectioned_transects_edit_transect.php');

/**
 *
 *
 * @package Client
 * @subpackage PrebuiltForms
 * Form for adding or editing the site details on a transect which contains a number of sections.
 */
class iform_ukbms_sectioned_transects_edit_transect extends iform_sectioned_transects_edit_transect {

  /**
   * Return the form metadata.
   * @return array The definition of the form.
   */
  public static function get_ukbms_sectioned_transects_edit_transect_definition() {
    return array(
      'title'=>'UKBMS Location editor',
      'category' => 'Sectioned Transects',
      'description'=>'Form for adding or editing the site details on a transect style location which has a number of sub-sections, but which can have various location types.'
    );
  }

  /**
   * Get the list of parameters for this form.
   * @return array List of parameters that this form requires.
   * @todo: Implement this method
   */
  public static function get_parameters() {
    $retVal = array_merge(
      parent::get_parameters(),
      array(
      	array(
          'name'=>'autogenerateCode',
          'caption'=>'Autogenerate Code',
          'description'=>'Autogenerate Location Codes.',
          'type' => 'boolean',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
      	array(
      		'name' => 'autogeneratePrefix',
      		'caption' => 'Autogenerate Prefix',
      		'description' => 'The prefix for the autogenerated code.',
      		'type'=>'string',
      		'group' => 'Transects Editor Settings',
          	'required' => false,
      		'default' => 'EBMS:'
      	),
      	array(
          'name'=>'main_type_term_1',
          'caption'=>'Location type term 1',
          'description'=>'Select the term used for the first main site location type.',
          'type' => 'select',
          'table'=>'termlists_term',
          'captionField'=>'term',
          'valueField'=>'term',
          'extraParams' => array('termlist_external_key'=>'indicia:location_types'),
          'required' => true,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'can_change_section_number_1',
          'caption'=>'Change section number 1',
          'description'=>'Select if sites of type 1 can change the number of sections.',
          'type' => 'boolean',
          'required' => false,
          'default' => true,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'section_number_1',
          'caption'=>'Section number 1',
          'description'=>'If the user can not change the number of sections for site type 1, then enter the fixed number of sections.',
          'type' => 'int',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'main_type_term_2',
          'caption'=>'Location type term 2',
          'description'=>'Select the term used for the second main site location type.',
          'type' => 'select',
          'table'=>'termlists_term',
          'captionField'=>'term',
          'valueField'=>'term',
          'extraParams' => array('termlist_external_key'=>'indicia:location_types'),
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'main_type_term_2_manager_only',
          'caption'=>'Second term manager only',
          'description'=>'Check if Location type term 2 is only to be available to users with the ' .
        		'Manager permission when creating a new site. Non managers will still be able to ' .
        		'edit the sites.',
          'type' => 'boolean',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
      	array(
          'name'=>'can_change_section_number_2',
          'caption'=>'Change section number 2',
          'description'=>'Select if sites of type 2 can change the number of sections.',
          'type' => 'boolean',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'section_number_2',
          'caption'=>'Section number 2',
          'description'=>'If the user can not change the number of sections for site type 2, then enter the fixed number of sections.',
          'type' => 'int',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'main_type_term_3',
          'caption'=>'Location type term 3',
          'description'=>'Select the term used for the third main site location type.',
          'type' => 'select',
          'table'=>'termlists_term',
          'captionField'=>'term',
          'valueField'=>'term',
          'extraParams' => array('termlist_external_key'=>'indicia:location_types'),
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'main_type_term_3_manager_only',
          'caption'=>'Third term manager only',
          'description'=>'Check if Location type term 3 is only to be available to users with the ' .
        		'Manager permission when creating a new site. Non managers will still be able to ' .
        		'edit the sites.',
          'type' => 'boolean',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
      	array(
          'name'=>'can_change_section_number_3',
          'caption'=>'Change section number 3',
          'description'=>'Select if sites of type 3 can change the number of sections.',
          'type' => 'boolean',
          'required' => false,
          'default' => true,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'section_number_3',
          'caption'=>'Section number 3',
          'description'=>'If the user can not change the number of sections for site type 3, then enter the fixed number of sections.',
          'type' => 'int',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'display_location_type',
          'caption'=>'Display location type',
          'description'=>'Where there is no location_type_id control displayed, check this to display the location type term.',
          'type' => 'boolean',
          'required' => false,
          'group'=>'Transects Editor Settings'
        ),
      	array(
      		'name'=>'autocalc_transect_length_attr_id',
      		'caption'=>'Location attribute to autocalc transect length',
      		'description'=>'Location attribute that stores the total transect length: summed from the lengths of the individual sections.',
      		'type'=>'select',
      		'table'=>'location_attribute',
      		'valueField'=>'id',
      		'captionField'=>'caption',
      		'group'=>'Transects Editor Settings',
      		'required'=>false
      	),
        array(
          'name'=>'custom_attribute_options',
          'caption'=>'Options for custom attributes',
          'description'=>'A list of additional options to pass through to custom attributes, one per line. Each option should be specified as '.
              'the attribute name followed by | then the option name, followed by = then the value. For example, smpAttr:1|class=control-width-5.',
          'type'=>'textarea',
      	  'group'=>'Transects Editor Settings'
        ),
        array(
          'name'=>'contact_blocks',
          'caption'=>'Form blocks to in the Contact details tab',
          'description'=>'A list of the blocks which need to be placed in the Contact details tab.',
          'type'=>'textarea',
          'group'=>'Transects Editor Settings',
          'siteSpecific'=>true,
          'required'=>false
        ),

    ));
    for($i= count($retVal)-1; $i>=0; $i--){
      switch($retVal[$i]['name']) {
        case 'transect_type_term':
        	unset($retVal[$i]);
        	break;
      	case 'survey_id':
          $retVal[$i]['description'] = 'The survey that data will be used to define custom attributes. This needs to match the survey used to submit visit data for sites of the first location type.';
          $retVal[$i]['group'] = 'Transects Editor Settings';
          break;
    	case 'georefDriver':
    	  $retVal[$i]['required']=false; // method of georef detection is to see if driver specified: allows ommision of area preferences.
          break;
    	default:
          break;
      }
    }
    return $retVal;
  }

  /**
   * Return the generated form output.
   * @param array $args List of parameter values passed through to the form depending on how the form has been configured.
   * This array always contains a value for language.
   * @param object $nid The Drupal node object's ID.
   * @param array $response When this form is reloading after saving a submission, contains the response from the service call.
   * Note this does not apply when redirecting (in this case the details of the saved object are in the $_GET data).
   * @return Form HTML.
   * @todo: Implement this method
   */
  public static function get_form($args, $nid, $response=null) {
    global $user;
    // use the js from the main form, until there is a deviation.
    // drupal_add_js(iform_client_helpers_path() . "prebuilt_forms/js/sectioned_transects_edit_transect.js");
    drupal_add_css(iform_client_helpers_path() . "prebuilt_forms/css/sectioned_transects_edit_transect.css");

    $checks=self::check_prerequisites();
    $args = self::getArgDefaults($args);
    if ($checks!==true)
      return $checks;
    iform_load_helpers(array('map_helper'));
    data_entry_helper::add_resource('jquery_form');
    self::$ajaxFormUrl = iform_ajaxproxy_url($nid, 'location');
    self::$ajaxFormSampleUrl = iform_ajaxproxy_url($nid, 'sample');
    $auth = data_entry_helper::get_read_write_auth($args['website_id'], $args['password']);
    $settings = array(
      'mainLocationType' => helper_base::get_termlist_terms($auth, 'indicia:location_types', array(empty($args['main_type_term_1']) ? 'Transect' : $args['main_type_term_1'])),
      'sectionLocationType' => helper_base::get_termlist_terms($auth, 'indicia:location_types', array(empty($args['section_type_term']) ? 'Section' : $args['section_type_term'])),
      'locationId' => isset($_GET['id']) ? $_GET['id'] : null,
      'canEditBody' => true,
      'canEditSections' => true, // this is specifically the number of sections: so can't delete or change the attribute value.
      // Allocations of Branch Manager are done by a person holding the managerPermission.
      'canAllocBranch' => $args['managerPermission']=="" || hostsite_user_has_permission($args['managerPermission']),
      // Allocations of Users are done by a person holding the managerPermission or the allocate Branch Manager.
      // The extra check on this for branch managers is done later
      'canAllocUser' => $args['managerPermission']=="" || hostsite_user_has_permission($args['managerPermission']),
      'canAccessContact' => true,
    );
    // WARNING!!!! we are making the assumption that the attributes are defined to be the same for all the location_types.
    $settings['attributes'] = data_entry_helper::getAttributes(array(
        'id' => $settings['locationId'],
        'valuetable'=>'location_attribute_value',
        'attrtable'=>'location_attribute',
        'key'=>'location_id',
        'fieldprefix'=>'locAttr',
        'extraParams'=>$auth['read'],
        'survey_id'=>$args['survey_id'],
        'location_type_id' => $settings['mainLocationType'][0]['id'],
        'multiValue' => true
    ));
    $settings['section_attributes'] = data_entry_helper::getAttributes(array(
        'valuetable'=>'location_attribute_value',
        'attrtable'=>'location_attribute',
        'key'=>'location_id',
        'fieldprefix'=>'locAttr',
        'extraParams'=>$auth['read'],
        'survey_id'=>$args['survey_id'],
        'location_type_id' => $settings['sectionLocationType'][0]['id'],
        'multiValue' => true
    ));
    if ($args['allow_user_assignment']) {
      if (false== ($settings['cmsUserAttr'] = extract_cms_user_attr($settings['attributes'])))
        return 'This form is designed to be used with the CMS User ID attribute setup for locations in the survey, or the "Allow users to be assigned to transects" option unticked.';
      // keep a copy of the cms user ID attribute so we can use it later.
      self::$cmsUserAttrId = $settings['cmsUserAttr']['attributeId'];
    }

    // need to check if branch allocation is active.
    if ($args['branch_assignment_permission'] != '') {
      if (false== ($settings['branchCmsUserAttr'] = self::extract_attr($settings['attributes'], "Branch CMS User ID")))
        return '<br />This form is designed to be used with either<br />1) the Branch CMS User ID attribute setup for locations in the survey, or<br />2) the "Permission name for Branch Manager" option left blank.<br />';
      // keep a copy of the branch cms user ID attribute so we can use it later.
      self::$branchCmsUserAttrId = $settings['branchCmsUserAttr']['attributeId'];
    } else self::$branchCmsUserAttrId = false;

    data_entry_helper::$javascript .= "indiciaData.sections = {};\n";
    $settings['sections']=array();
    $settings['numSectionsAttr'] = "";
    $settings['maxSectionCount'] = $args['maxSectionCount'];
    $settings['autocalcSectionLengthAttrId'] = empty($args['autocalc_section_length_attr_id']) ? 0 : $args['autocalc_section_length_attr_id'];
    if ($settings['autocalcSectionLengthAttrId'] > 0)
    	data_entry_helper::$javascript .= "$('#locAttr\\\\:".$settings['autocalcSectionLengthAttrId']."').attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
    $settings['autocalcTransectLengthAttrId'] = empty($args['autocalc_transect_length_attr_id']) ? 0 : $args['autocalc_transect_length_attr_id'];
    $settings['autocalcTransectLengthAttrName'] = 0;

    $settings['defaultSectionGridRef'] = empty($args['default_section_grid_ref']) ? 'parent' : $args['default_section_grid_ref'];
    if ($settings['locationId']) {
      $fixedSectionNumber = false;
      data_entry_helper::load_existing_record($auth['read'], 'location', $settings['locationId']);
      $settings['walks'] = data_entry_helper::get_population_data(array(
        'table' => 'sample',
        'extraParams' => $auth['read'] + array('view'=>'detail','location_id'=>$settings['locationId'],'deleted'=>'f'),
        'nocache' => true
      ));
      // Work out permissions for this user: note that canAllocBranch setting effectively shows if a manager.
      if(!$settings['canAllocBranch']) {
        // Check whether I am a normal user and it is allocated to me, and also if I am a branch manager and it is allocated to me.
        $settings['canEditBody'] = false;
        $settings['canEditSections'] = false;
        $settings['canAccessContact'] = false;
        if($args['allow_user_assignment'] &&
            count($settings['walks']) == 0 &&
            isset($settings['cmsUserAttr']['default']) &&
            !empty($settings['cmsUserAttr']['default'])) {
          foreach($settings['cmsUserAttr']['default'] as $value) { // multi value
            if($value['default'] == $user->uid) { // comparing string against int so no triple equals
              $settings['canEditBody'] = true;
              $settings['canEditSections'] = true;
              break;
            }
          }
        }
        if($args['allow_user_assignment'] &&
            isset($settings['cmsUserAttr']['default']) &&
            !empty($settings['cmsUserAttr']['default'])) {
          foreach($settings['cmsUserAttr']['default'] as $value) { // multi value
            if($value['default'] == $user->uid) { // comparing string against int so no triple equals
              $settings['canAccessContact'] = true;
              break;
            }
          }
        }
        // If a Branch Manager and not a main manager, then can't edit the number of sections
        if($args['branch_assignment_permission'] != '' &&
            hostsite_user_has_permission($args['branch_assignment_permission']) &&
            isset($settings['branchCmsUserAttr']['default']) &&
            !empty($settings['branchCmsUserAttr']['default'])) {
          foreach($settings['branchCmsUserAttr']['default'] as $value) { // now multi value
            if($value['default'] == $user->uid) { // comparing string against int so no triple equals
              $settings['canEditBody'] = true;
              $settings['canAllocUser'] = true;
              $settings['canAccessContact'] = true;
              break;
            }
          }
        }
        // but if the location type is a fixed number type, then canEditSections is always false
        for($i = 1; $i < 4; $i++){
          if(!empty($args['main_type_term_'.$i])) {
            $type = helper_base::get_termlist_terms($auth, 'indicia:location_types', array($args['main_type_term_'.$i]));
            if(data_entry_helper::$entity_to_load['location:location_type_id'] == $type[0]['id'] &&
                (!isset($args['can_change_section_number_'.$i]) || !$args['can_change_section_number_'.$i])) {
              $settings['canEditSections'] = false;
              $fixedSectionNumber = $args['section_number_'.$i];
            }
          }
        }
      } // for an admin user the defaults apply, which will be can do everything.
      // find the number of sections attribute.
      foreach($settings['attributes'] as $attr) {
        if ($attr['caption']==='No. of sections') {
          $settings['numSectionsAttr'] = $attr['fieldname'];
          if($fixedSectionNumber) {
            for ($i=1; $i<=$fixedSectionNumber; $i++)
              $settings['sections']["S$i"]=null;
            data_entry_helper::$javascript .= "$('#".str_replace(':','\\\\:',$attr['id'])."').val($fixedSectionNumber).attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
          } else {
            for ($i=1; $i<=$attr['displayValue']; $i++) {
              $settings['sections']["S$i"]=null;
            }
            $existingSectionCount = empty($attr['displayValue']) ? 1 : $attr['displayValue'];
            data_entry_helper::$javascript .= "$('#".str_replace(':','\\\\:',$attr['id'])."').attr('min',$existingSectionCount).attr('max',".$args['maxSectionCount'].");\n";
            if(!$settings['canEditSections'])
              data_entry_helper::$javascript .= "$('#".str_replace(':','\\\\:',$attr['id'])."').attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
          }
        }
        if (isset($args['autocalc_transect_length_attr_id']) &&
        		$args['autocalc_transect_length_attr_id'] != '' &&
        		$attr['attributeId']==$args['autocalc_transect_length_attr_id']) {
          $settings['autocalcTransectLengthAttrName'] = $attr['fieldname'];
          data_entry_helper::$javascript .= "$('#".str_replace(':','\\\\:',$attr['id'])."').attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
        }
      }
      $sections = data_entry_helper::get_population_data(array(
        'table' => 'location',
        'extraParams' => $auth['read'] + array('view'=>'detail','parent_id'=>$settings['locationId'],'deleted'=>'f','orderby'=>'id'),
        'nocache' => true
      ));
      foreach($sections as $section) {
        $code = $section['code'];
        if(in_array($section['centroid_sref_system'], array('osgb','osie')))
        	$section['centroid_sref_system'] = strtoupper($section['centroid_sref_system']);
        data_entry_helper::$javascript .= "indiciaData.sections.$code = {'geom':'".$section['boundary_geom']."','id':'".$section['id']."','sref':'".$section['centroid_sref']."','system':'".$section['centroid_sref_system']."'};\n";
        $settings['sections'][$code]=$section;

        if (isset($args['autocalc_transect_length_attr_id']) &&
        		$args['autocalc_transect_length_attr_id'] != '') {
    		$section_attributes = data_entry_helper::getAttributes(array(
		        'valuetable'=>'location_attribute_value',
		        'attrtable'=>'location_attribute',
		        'key'=>'location_id',
		        'fieldprefix'=>'locAttr',
		        'extraParams'=>$auth['read'] + array('id' => $args['autocalc_section_length_attr_id']),
		        'survey_id'=>$args['survey_id'],
		        'location_type_id' => $settings['sectionLocationType'][0]['id'],
		        'id' => $section['id']
		    ), false);
    		if(count($section_attributes) > 0 &&
    				$section_attributes[0]['default'] != '')
    			data_entry_helper::$javascript .= "indiciaData.sections.".$code.".sectionLen = ".$section_attributes[0]['default']." ;\n";
        }
      }
    } else { // not an existing site therefore no walks or sections. On initial save, no section data is created.
      foreach($settings['attributes'] as $attr) {
        if ($attr['caption']==='No. of sections') {
          $settings['numSectionsAttr'] = $attr['fieldname'];
          data_entry_helper::$javascript .= "$('#".str_replace(':','\\\\:',$attr['id'])."').attr('min',1).attr('max',".$args['maxSectionCount'].");\n";
        }
        if ($attr['attributeId']==$args['autocalc_transect_length_attr_id']) {
          $settings['autocalcTransectLengthAttrName'] = $attr['fieldname'];
          data_entry_helper::$javascript .= "$('#".str_replace(':','\\\\:',$attr['id'])."').attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
        }
      }
      $settings['walks'] = array();
    }
    if ($settings['numSectionsAttr'] === '') {
      for ($i=1; $i<=$settings['maxSectionCount']; $i++) {
        $settings['sections']["S$i"]=null;
      }
    }
    $r = '<div id="controls">';
    $contact='';
    $siteTab = self::get_site_tab($auth, $args, $settings, $contact);
    $headerOptions = array('tabs'=>array('#site-details'=>lang::get('Site Details')));
    if ($settings['locationId']) {
      $headerOptions['tabs']['#your-route'] = lang::get('Your Route');
      if(count($settings['section_attributes']) > 0) {
        $headerOptions['tabs']['#section-details'] = lang::get('Section Details');
      }
      if($settings['canAccessContact'] && $contact !== '') {
        $headerOptions['tabs']['#contact-details'] = lang::get('Contact Details');
      }
    }
    if (count($headerOptions['tabs'])) {
      $r .= data_entry_helper::tab_header($headerOptions);
      data_entry_helper::enable_tabs(array(
          'divId'=>'controls',
          'style'=>'Tabs',
          'progressBar' => isset($args['tabProgress']) && $args['tabProgress']==true
      ));
    }
    $r .= $siteTab;
    if ($settings['locationId']) {
      $r .= self::get_your_route_tab($auth, $args, $settings);
      if(count($settings['section_attributes']) > 0) {
        $r .= self::get_section_details_tab($auth, $args, $settings);
      }
      if($settings['canAccessContact'] && $contact !== '')
          $r .= self::get_contact_details_tab($auth, $args, $settings, $contact);
    }
    $r .= '</div>'; // controls
    data_entry_helper::enable_validation('input-form');
    if (function_exists('drupal_set_breadcrumb')) {
      $breadcrumb = array();
      $breadcrumb[] = l(lang::get('Home'), '<front>');
      $breadcrumb[] = l(lang::get('Sites'), $args['sites_list_path']);
      if ($settings['locationId'])
        $breadcrumb[] = data_entry_helper::$entity_to_load['location:name'];
      else
        $breadcrumb[] = lang::get('New Site');
      drupal_set_breadcrumb($breadcrumb);
    }
    // Inform JS where to post data to for AJAX form saving
    data_entry_helper::$javascript .= 'indiciaData.ajaxFormPostUrl="'.self::$ajaxFormUrl."\";\n";
    data_entry_helper::$javascript .= 'indiciaData.ajaxFormPostSampleUrl="'.self::$ajaxFormSampleUrl."\";\n";
    data_entry_helper::$javascript .= 'indiciaData.website_id="'.$args['website_id']."\";\n";
    data_entry_helper::$javascript .= "indiciaData.indiciaSvc = '".data_entry_helper::$base_url."';\n";
    data_entry_helper::$javascript .= "indiciaData.readAuth = {nonce: '".$auth['read']['nonce']."', auth_token: '".$auth['read']['auth_token']."'};\n";
    data_entry_helper::$javascript .= "indiciaData.currentSection = '';\n";
    data_entry_helper::$javascript .= "indiciaData.sectionTypeId = '".$settings['sectionLocationType'][0]['id']."';\n";
    data_entry_helper::$javascript .= "indiciaData.sectionDeleteConfirm = \"".lang::get('Are you sure you wish to delete section')."\";\n";
    data_entry_helper::$javascript .= "indiciaData.sectionInsertConfirm = \"".lang::get('Are you sure you wish to insert a new section after section')."\";\n";
    data_entry_helper::$javascript .= "indiciaData.routeChangeConfirm = \"".lang::get('Do you wish to save the currently unsaved modification you have made to the Route, before selecting the new Section? Select Yes to save the Route, or No to abandon the Route modification.')."\";\n";
    data_entry_helper::$javascript .= "indiciaData.routeChangeConfirmCancel = \"".lang::get('Do you wish to save the currently unsaved modification you have made to the Route, before selecting the new Section? Select Yes to save the Route, No to abandon the Route modification, or Cancel to keep the Route modification without saving it and without swapping to the new Section.')."\";\n";
    data_entry_helper::$javascript .= "indiciaData.sectionChangeConfirm = \"".lang::get('Do you wish to save the currently unsaved modifications you have made to the Section Details, before selecting the new Section? Select Yes to save the Section Details, or No to abandon the Section Detail modifications.')."\";\n";
    data_entry_helper::$javascript .= "indiciaData.sectionChangeConfirmCancel = \"".lang::get('Do you wish to save the currently unsaved modifications you have made to the Section Details, before selecting the new Section? Select Yes to save the Section Details, No to abandon the Section Detail modifications, or Cancel to keep the Section Details modifications without saving them and without swapping to the new Section.')."\";\n";
    data_entry_helper::$javascript .= "indiciaData.numSectionsAttrName = \"".$settings['numSectionsAttr']."\";\n";
    data_entry_helper::$javascript .= "indiciaData.maxSectionCount = \"".$settings['maxSectionCount']."\";\n";
    data_entry_helper::$javascript .= "indiciaData.autocalcSectionLengthAttrId = ".$settings['autocalcSectionLengthAttrId'].";\n";
    data_entry_helper::$javascript .= "indiciaData.autocalcTransectLengthAttrId = ".$settings['autocalcTransectLengthAttrId'].";\n";
    data_entry_helper::$javascript .= "indiciaData.autocalcTransectLengthAttrName = \"".$settings['autocalcTransectLengthAttrName']."\";\n";
    data_entry_helper::$javascript .= "indiciaData.defaultSectionGridRef = '".$settings['defaultSectionGridRef']."';\n";
    if ($settings['locationId'])
      data_entry_helper::$javascript .= "selectSection('S1', true);\n";

    return $r;
  }

  private static function get_site_tab($auth, $args, $settings, &$contact) {
    $r = '<div id="site-details" class="ui-helper-clearfix">';
    $r .= '<form method="post" id="input-form">';
    $r .= $auth['write'];
    $r .= '<div id="cols" class="ui-helper-clearfix"><div class="left" style="width: 54%">';
    $r .= '<fieldset><legend>'.lang::get('Site Details').'</legend>';
    $r .= "<input type=\"hidden\" name=\"website_id\" value=\"".$args['website_id']."\" />\n";
    $typeTerms = array();
    if(!empty($args['main_type_term_1'])) $typeTerms[] = $args['main_type_term_1'];
    if(!empty($args['main_type_term_2']) &&
    		(empty($args['main_type_term_2_manager_only']) ||
    			!$args['main_type_term_2_manager_only'] ||
    			(isset($args['managerPermission']) && $args['managerPermission']!="" && hostsite_user_has_permission($args['managerPermission']))))
    	$typeTerms[] = $args['main_type_term_2'];
    if(!empty($args['main_type_term_3']) &&
    		(empty($args['main_type_term_3_manager_only']) ||
    			!$args['main_type_term_3_manager_only'] ||
    			(isset($args['managerPermission']) && $args['managerPermission']!="" && hostsite_user_has_permission($args['managerPermission']))))
    	$typeTerms[] = $args['main_type_term_3'];
    $typeTermIDs = helper_base::get_termlist_terms($auth, 'indicia:location_types', $typeTerms);
    $lookUpValues = array('' => '<' . lang::get('please select') . '>');
    foreach($typeTermIDs as $termDetails){
      $lookUpValues[$termDetails['id']] = $termDetails['term'];
    }
    // if location is predefined, can not change unless a 'managerPermission'
    $canEditType = !$settings['locationId'] ||
                   (isset($args['managerPermission']) && $args['managerPermission']!= '' && hostsite_user_has_permission($args['managerPermission']));
    $display_location_type_id = false;
    if($canEditType) {
      if(count($lookUpValues)>2) { // includes the "please select" empty option
        $r .= data_entry_helper::select(array(
            'label' => lang::get('Site Type'),
            'id' => 'location_type_id',
      		'fieldname' => 'location:location_type_id',
            'lookupValues' => $lookUpValues
        ));
        data_entry_helper::$javascript .= "$('#location_type_id').change(function(){
  switch($(this).val()){\n";
        for($i = 1; $i < 4; $i++){
         if(!empty($args['main_type_term_'.$i])) {
          $type = helper_base::get_termlist_terms($auth, 'indicia:location_types', array($args['main_type_term_'.$i]));
          data_entry_helper::$javascript .= "    case \"".$type[0]['id']."\":\n";
          if(!isset($args['can_change_section_number_'.$i]) || !$args['can_change_section_number_'.$i]) {
            if ($settings['locationId'])
              // not saved yet, so no sections yet created, hence no need to worry about existing value. make number attribute readonly. set value. min value will be 1.
              data_entry_helper::$javascript .= "      var minValue = $('[name=".str_replace(':','\\\\:',$settings['numSectionsAttr'])."]').attr('min');
      if(minValue > ".$args['section_number_'.$i].") { // existing value is greater than one we want to set
        alert('You are reducing the number of sections below that already existing. Please use the Remove Section button on the Your Route tab to reduce the number of sections to ".$args['section_number_'.$i]." before changing the Site type');
        return false;
      }
      $('[name=".str_replace(':','\\\\:',$settings['numSectionsAttr'])."]').val(".$args['section_number_'.$i].").attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
            else
              // not saved yet, so no sections yet created, hence no need to worry about existing value. make number attribute readonly. set value. min value will be 1.
              data_entry_helper::$javascript .= "      $('[name=".str_replace(':','\\\\:',$settings['numSectionsAttr'])."]').val(".$args['section_number_'.$i].").attr('readonly','readonly').css('color','graytext').css('background-color','#d0d0d0');\n";
          } else {
            // user modifiable number of sections. value of attribute is left alone: don't have to worry att his point whether existing data.
            data_entry_helper::$javascript .= "      $('[name=".str_replace(':','\\\\:',$settings['numSectionsAttr'])."]').removeAttr('readonly').css('color','').css('background-color','');\n";
          }
          data_entry_helper::$javascript .= "      break;\n";
         }
        }
        data_entry_helper::$javascript .= "    default: break;
  };
  return true;
});\n";
      } else if(!$settings['locationId']) { // new site, only one possible value
      	$r .= '<input type="hidden" name="location:location_type_id" id="location:location_type_id" value="'.$typeTermIDs[0]['id'].'" />';
      	$display_location_type_id = $typeTermIDs[0]['id'];
      } else {
      	// else user can edit the location type for an existing site but only one option -> just leave the location_type_id alone: don't even include in the data submitted.
      	$display_location_type_id = data_entry_helper::$entity_to_load['location:location_type_id'];
      }
    } else {
    	// else user can't edit the location_type_id for an existing site -> just leave the location_type_id alone: don't even include in the data submitted.
      	$display_location_type_id = data_entry_helper::$entity_to_load['location:location_type_id'];
    }
    if($display_location_type_id && !empty($args['display_location_type']) && $args['display_location_type']) {
    	$list = data_entry_helper::get_population_data(array(
    			'table' => 'termlist',
    			'extraParams' => $auth['read'] + array('external_key' => 'indicia:location_types')
    	));
    	$terms = data_entry_helper::get_population_data(array(
    			'table' => 'termlists_term',
    			'extraParams' => $auth['read'] + array(
    				'view' => 'detail',
    				'termlist_id' => $list[0]['id'],
    				'id' => $display_location_type_id)
    	));
    	$r .= str_replace('%s', $terms[0]['term'], '<h3>'.lang::get('This site is of type &quot;%s&quot;.').'</h3>');
    }
    if ($settings['locationId'])
      $r .= '<input type="hidden" name="location:id" id="location:id" value="'.$settings['locationId']."\" />\n";
    $r .= data_entry_helper::text_input(array(
      'fieldname' => 'location:name',
      'label' => lang::get('Site Name'),
      'class' => 'control-width-4 required',
      'disabled' => $settings['canEditBody'] ? '' : ' disabled="disabled" '
    ));
    if (!$settings['canEditBody']){
      $r .= '<p>'.lang::get('This site cannot be edited because there are walks recorded on it. Please contact the site administrator if you think there are details which need changing.').'</p>';
    } else if(count($settings['walks']) > 0) { // can edit it
      $r .= '<p>'.lang::get('This site has walks recorded on it. Please do not change the site details without considering the impact on the existing data.').'</p>';
    }
    $list = explode(',', str_replace(' ', '', $args['spatial_systems']));
    foreach($list as $system) {
      $systems[$system] = lang::get($system);
    }
    if(isset(data_entry_helper::$entity_to_load['location:centroid_sref_system']) &&
        in_array(data_entry_helper::$entity_to_load['location:centroid_sref_system'], array('osgb','osie')))
      data_entry_helper::$entity_to_load['location:centroid_sref_system'] = strtoupper(data_entry_helper::$entity_to_load['location:centroid_sref_system']);
    $r .= data_entry_helper::sref_and_system(array(
      'fieldname' => 'location:centroid_sref',
      'geomFieldname' => 'location:centroid_geom',
      'label' => lang::get('Grid Ref.'),
      'systems' => $systems,
      'class' => 'required',
      'helpText' => lang::get('Click on the map to set the central grid reference.'),
      'disabled' => $settings['canEditBody'] ? '' : ' disabled="disabled" '
    ));
    // TODO find way to identify the country.
    if(isset($args['autogenerateCode'])  && $args['autogenerateCode']) {
    	if(!$settings['locationId']) {
    		$otherSites = data_entry_helper::get_population_data(array(
    				'table' => 'location',
    				'extraParams' => $auth['read'] + array('view'=>'detail','deleted'=>'f', 'location_type_id'=>$typeTermIDs[0]['id']),
    				'columns'=>'code',
    				'nocache' => true
    		));
    		$val = 1;
    		foreach($otherSites as $otherSite) {
    			if(strncmp($otherSite['code'],$args['autogeneratePrefix'],strlen($args['autogeneratePrefix']))==0) {
    				$myVal = intval(substr($otherSite['code'],strlen($args['autogeneratePrefix'])));
    				if($val<=$myVal) $val = $myVal+1;
    			}
    		}
    		data_entry_helper::$entity_to_load['location:code'] = $args['autogeneratePrefix'].$val;
	    }
	    $locCodeDefn = array(
    			'fieldname' => 'location:code',
    			'label' => lang::get('Site Code'),
    			'class' => 'control-width-4',
    			'disabled' => hostsite_user_has_permission($args['managerPermission']) ? '' : ' readonly="readonly" ',
    			'helpText' => lang::get('An internal reference; this value cannot be edited')
    	);
	    if(!hostsite_user_has_permission($args['managerPermission'])) {
	    	$locCodeDefn['disabled'] = ' readonly="readonly" ';
    		$locCodeDefn['helpText'] = lang::get('An internal reference; this value cannot be edited');
        	data_entry_helper::$javascript .= "$('[name=location\\\\:code]').css('color','graytext').css('background-color','#d0d0d0');\n";
	    }
    	$r .= data_entry_helper::text_input($locCodeDefn);
    } else {
      if ($settings['locationId'] && data_entry_helper::$entity_to_load['location:code']!='' && data_entry_helper::$entity_to_load['location:code'] != null) {
        $r .= data_entry_helper::text_input(array(
          'fieldname' => 'location:code',
          'label' => lang::get('Site Code'),
          'class' => 'control-width-4',
          'disabled' => ' readonly="readonly" '
        ));
        data_entry_helper::$javascript .= "$('[name=location\\\\:code]').css('color','graytext').css('background-color','#d0d0d0');\n";
      } else
        $r .= "<p>".lang::get('The Site Code will be allocated by the Administrator.')."</p>";
    }

    // setup the map options
    $options = iform_map_get_map_options($args, $auth['read']);

    $blockOptions = array();
    if (isset($args['custom_attribute_options']) && $args['custom_attribute_options']) {
    	$blockOptionList = explode("\n", $args['custom_attribute_options']);
    	foreach($blockOptionList as $opt) {
    		$tokens = explode('|', $opt);
    		$optvalue = explode('=', $tokens[1]);
    		$blockOptions[$tokens[0]][$optvalue[0]] = $optvalue[1];
    	}
    }

    // find the form blocks that need to go into the contact tab.
    $contact = '';
    if(isset($args['contact_blocks']) && $args['contact_blocks'] !== '') {
        $contactBlocks = explode("\n", $args['contact_blocks']);
        foreach ($contactBlocks as $block) {
            $contact .= get_attribute_html($settings['attributes'], $args, array('extraParams'=>$auth['read']), $block, $blockOptions);
        }
    }
    // find the form blocks that need to go below the map.
    $bottom = '';
    $bottomBlocks = explode("\n", isset($args['bottom_blocks']) ? $args['bottom_blocks'] : '');
    foreach ($bottomBlocks as $block) {
      $bottom .= get_attribute_html($settings['attributes'], $args, array('extraParams'=>$auth['read'], 'disabled' => $settings['canEditBody'] ? '' : ' disabled="disabled" '), $block, $blockOptions);
    }
    // other blocks to go at the top, next to the map
    if(isset($args['site_help']) && $args['site_help'] != ''){
      $r .= '<p class="ui-state-highlight page-notice ui-corner-all">'.t($args['site_help']).'</p>';
    }
    $r .= get_attribute_html($settings['attributes'], $args, array('extraParams'=>$auth['read']), null, $blockOptions);
    $r .= '</fieldset>';
    $r .= "</div>"; // left
    $r .= '<div class="right" style="width: 44%">';
    if(isset($args['georefDriver']) && $args['georefDriver']!='' && !$settings['locationId']) {
      $help = t('Use the search box to find a nearby town or village, then drag the map to pan and click on the map to set the centre grid reference of the transect. '.
          'Alternatively if you know the grid reference you can enter it in the Grid Ref box on the left.');
      $r .= '<p class="ui-state-highlight page-notice ui-corner-all">'.$help.'</p>';
      $r .= data_entry_helper::georeference_lookup(iform_map_get_georef_options($args, $auth['read']));
    }
    if(isset($args['maxPrecision']) && $args['maxPrecision'] != ''){
      $options['clickedSrefPrecisionMax'] = $args['maxPrecision'];
    }
    if(isset($args['minPrecision']) && $args['minPrecision'] != ''){
      $options['clickedSrefPrecisionMin'] = $args['minPrecision'];
    }
    $olOptions = iform_map_get_ol_options($args);
    $options['clickForSpatialRef']=$settings['canEditBody'];
    $r .= map_helper::map_panel($options, $olOptions);
    $r .= '</div></div>'; // right
    if (!empty($bottom))
      $r .= $bottom;
    if ($args['branch_assignment_permission'] != '') {
      if ($settings['canAllocBranch'] || $settings['locationId'])
        $r .= self::get_branch_assignment_control($auth['read'], $settings['branchCmsUserAttr'], $args, $settings);
    }
    if ($args['allow_user_assignment']) {
      if ($settings['canAllocUser']) {
        $r .= self::get_user_assignment_control($auth['read'], $settings['cmsUserAttr'], $args);
      } else if (!$settings['locationId']) {
        // for a new record, we need to link the current user to the location if they are not admin.
        global $user;
        $r .= '<input type="hidden" name="locAttr:'.self::$cmsUserAttrId.'" value="'.$user->uid.'">';
      }
    }
    if ($settings['canEditBody']) {
      if (lang::get('LANG_DATA_PERMISSION') !== 'LANG_DATA_PERMISSION') {
        $r .= '<p>' . lang::get('LANG_DATA_PERMISSION') . '</p>';
      }
      $r .= '<button type="submit" class="indicia-button right">'.lang::get('Save').'</button>';
    }

    if($settings['canEditBody'] && $settings['locationId'])
      $r .= '<button type="button" class="indicia-button right" id="delete-transect">'.lang::get('Delete').'</button>' ;
    $r .='</form>';
    $r .= '</div>'; // site-details
    // This must go after the map panel, so it has created its toolbar
    data_entry_helper::$onload_javascript .= "$('#current-section').change(selectSection);\n";
    if($settings['canEditBody'] && $settings['locationId']) {
      $walkIDs = array();
      foreach($settings['walks'] as $walk)
        $walkIDs[] = $walk['id'];
      $sectionIDs = array();
      foreach($settings['sections'] as $code=>$section)
        $sectionIDs[] = $section['id'];
      data_entry_helper::$javascript .= "
deleteSurvey = function(){
  if(confirm(\"".(count($settings['walks']) > 0 ? count($settings['walks']).' '.lang::get('walks will also be deleted when you delete this location.').' ' : '').lang::get('Are you sure you wish to delete this location?')."\")){
    deleteWalks([".implode(',',$walkIDs)."]);
    deleteSections([".implode(',',$sectionIDs)."]);
    $('#delete-transect').html('Deleting Site');
    deleteLocation(".$settings['locationId'].");
    $('#delete-transect').html('Done');
    window.location='".url($args['sites_list_path'])."';
  };
};
$('#delete-transect').click(deleteSurvey);
";
    }
    return $r;
  }

  protected static function get_your_route_tab($auth, $args, $settings) {
  	$r = '<div id="your-route" class="ui-helper-clearfix">';
  	$olOptions = iform_map_get_ol_options($args);
  	$options = iform_map_get_map_options($args, $auth['read']);
  	$options['divId'] = 'route-map';
  	$options['toolbarDiv'] = 'top';
  	// $options['tabDiv']='your-route';
  	$options['gridRefHint']=true;
  	if ($settings['canEditBody']){
  	    if (lang::get('LANG_DATA_PERMISSION') !== 'LANG_DATA_PERMISSION') {
  	        $r .= '<p>' . lang::get('LANG_DATA_PERMISSION') . '</p>';
  	    }
  		$options['toolbarPrefix'] = parent::section_selector($settings, 'section-select-route') .
  									'<br/>'.
  									'<input class="save-route form-button" type="button" value="Save Route">'.
  									'<input class="complete-route-details form-button" type="button" value="Complete section details">';
  		if($settings['canEditSections'] && count($settings['sections'])<$args['maxSectionCount'] && $settings['numSectionsAttr'] != "") // do not allow insertion of section if it exceeds max number, or if the is no section number attribute
  			$options['toolbarPrefix'] .= '<input type="button" value="'.lang::get('Insert Section').'" class="insert-section form-button" title="'.lang::get('This inserts an extra section after the currently selected section. All subsequent sections are renumbered, increasing by one. All associated occurrences are kept with the moved sections. This can be used to facilitate the splitting of this section.').'">';
  		$options['toolbarPrefix'] .= '<input type="button" value="'.lang::get('Erase Route').'" class="erase-route form-button" title="'.lang::get('If the Draw Line control is active, this will erase each drawn point one at a time. If not active, then this will erase the whole highlighted route. This keeps the Section, allowing you to redraw the route for it.').'">';
  		if($settings['canEditSections'] && count($settings['sections'])>1 && $settings['numSectionsAttr'] != "") // do not allow deletion of last section, or if the is no section number attribute
  			$options['toolbarPrefix'] .= '<input type="button" value="'.lang::get('Remove Section').'" class="remove-section form-button" title="'.lang::get('Completely remove the highlighted section. The total number of sections will be reduced by one. The form will be reloaded after the section is deleted.').'">';

  		// also let the user click on a feature to select it. The highlighter just makes it easier to select one.
  		// these controls are not present in read-only mode: all you can do is look at the map.
  		$options['standardControls'][] = 'selectFeature';
  		$options['standardControls'][] = 'hoverFeatureHighlight';
  		$options['standardControls'][] = 'drawLine';
  		$options['standardControls'][] = 'modifyFeature';
  		$options['switchOffSrefRetrigger'] = true;
  		$help = lang::get('Select a section from the list then click on the map to draw the route and double click to finish. '.
  				'You can also select a section using the &quot;Query&quot; tool to click on the section lines. If you make a mistake in the middle '.
  				'of drawing a route, then you can use the &quot;Erase Route&quot; button to remove the last point drawn. After a route has been '.
  				'completed use the &quot;Modify feature&quot; tool to correct the line shape (either by dragging one of the circles along the '.
  				'line to form the correct shape, or by placing the mouse over a circle and pressing the &quotDelete&quot button on your keyboard '.
  				'to remove that point). Alternatively you could just redraw the line - this new line will then replace the old one '.
  				'completely. If you are not in the middle of drawing a line, the &quot;Erase Route&quot; button will erase the whole route for the '.
  				'currently selected section.').
  				($settings['numSectionsAttr'] != "" ?
  						'<br />'.(count($settings['sections'])>1 ?
  								lang::get('The &quot;Remove Section&quot; button will remove the section completely, reducing the number of sections by one.').' '
  								: '').
  						lang::get('To increase the number of sections, either return to the &quot;Site Details&quot; tab, and increase the value in the '.
  								'&quot;No. of sections&quot; field there (which will add new sections to the end of the list), or use the '.
  								'&quot;Insert Section&quot; button to add a new section immediately after the currently selected section.')
  						: '').
  				'<br />'.lang::get('Once all route sections are drawn, select the &quot;Section Details&quot; tab (or use the &quot;Complete section details&quot; button) to complete the route setup.');
  		$r .= '<p class="ui-state-highlight page-notice ui-corner-all">'.$help.'</p>';
  	}
  	$options['clickForSpatialRef'] = false;
  	// override the opacity so the parent square does not appear filled in.
  	$options['fillOpacity'] = 0;
  	// override the map height and buffer size, which are specific to this map.
  	$options['height'] = $args['route_map_height'];
  	$options['maxZoomBuffer'] = $args['route_map_buffer'];

  	$r .= map_helper::map_panel($options, $olOptions);
  	$r .= '<button class="indicia-button right" type="button" title="'.
  		lang::get('Returns to My Sites page. Remember to save any changes to the Site details, Route and/or Section details first.').
  		'" onclick="window.location.href=\'' . url($args['sites_list_path']) . '\'">'.lang::get('Finish').'</button>';
  	$r .= '</div>';
  	return $r;
  }

  protected static function get_contact_details_tab($auth, $args, $settings, $contact) {
      $r = '<div id="contact-details" class="ui-helper-clearfix">';
      $r .= '<form method="post" id="input-form-2">';
      $r .= $auth['write'];
      $r .= '<fieldset><legend>'.lang::get('Contact Details').'</legend>';
      $r .= '<input type="hidden" name="location:id" value="'.$settings['locationId'].'" />' . PHP_EOL;
      $r .= '<input type="hidden" name="website_id" value="'.$args['website_id'].'" />' . PHP_EOL;
      $r .= '<input type="hidden" name="location:centroid_sref_system" value="'.data_entry_helper::$entity_to_load['location:centroid_sref_system'].'" />' . PHP_EOL;
      $r .= '<input type="hidden" name="location:centroid_sref" value="'.data_entry_helper::$entity_to_load['location:centroid_sref'].'" />' . PHP_EOL;
      $r .= '<input type="hidden" name="location:centroid_geom" value="'.data_entry_helper::$entity_to_load['location:centroid_geom'].'" />' . PHP_EOL;
      $r .= $contact;
      if (lang::get('LANG_DATA_PERMISSION') !== 'LANG_DATA_PERMISSION') {
          $r .= '<p>' . lang::get('LANG_DATA_PERMISSION') . '</p>';
      }
      $r .= '<input type="submit" value="'.lang::get('Save').'" class="form-button right" id="submit-contact" />';
      $r .= '</fieldset></form>';
      $r .= '</div>';
      return $r;
  }
  
}
